package probs.prob_26_50
{
	import probs.Problem;

	/**
	 * <B>Problem 45</B>
	 <div class="problem_content" role="problem">
	 <p>Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:</p>
	 <table>
	 <tbody><tr>
	 <td>Triangle</td>
	 <td>&nbsp;</td>
	 <td>T<sub><i>n</i></sub>=<i>n</i>(<i>n</i>+1)/2</td>
	 <td>&nbsp;</td>
	 <td>1, 3, 6, 10, 15, ...</td>
	 </tr>
	 <tr>
	 <td>Pentagonal</td>
	 <td>&nbsp;</td>
	 <td>P<sub><i>n</i></sub>=<i>n</i>(3<i>n</i><img src="images/symbol_minus.gif" width="9" height="3" alt="−" border="0" style="vertical-align:middle;">1)/2</td>
	 <td>&nbsp;</td>
	 <td>1, 5, 12, 22, 35, ...</td>
	 </tr>
	 <tr>
	 <td>Hexagonal</td>
	 <td>&nbsp;</td>
	 <td>H<sub><i>n</i></sub>=<i>n</i>(2<i>n</i><img src="images/symbol_minus.gif" width="9" height="3" alt="−" border="0" style="vertical-align:middle;">1)</td>
	 <td>&nbsp;</td>
	 <td>1, 6, 15, 28, 45, ...</td>
	 </tr>
	 </tbody></table>
	 <p>It can be verified that T<sub>285</sub> = P<sub>165</sub> = H<sub>143</sub> = 40755.</p>
	 <p>Find the next triangle number that is also pentagonal and hexagonal.</p>
	 </div>
	 * @author Tim Wu <a href="http://wuzhiwei.net">http://wuzhiwei.net</a><br>
	 * 
	 */
	public class Prob45 extends Problem
	{
		private var _T:Array = [];
		private var _P:Array = [];
		private var _H:Array = [];
		
		public function Prob45()
		{
			for( var n:int = 286;n<100000;n++)
			{
				_T.push( n*(n+1)/2 );
			}
			for (n = 166;n<100000;n++)
			{
				_P.push( n*(3*n-1)/2 );
			}
			for (n = 143;n<100000;n++)
			{
				_H.push( n*(2*n-1) );
			}
			
			for (var i:int = 0;i<_H.length;i++)
			{
				if( _T.indexOf(_H[i])>=0 && _P.indexOf(_H[i])>=0 )
				{
					super.showAnswer(_H[i]);
					break;
				}
			}
		}
	}
}