package probs.prob_1_25
{
	import flash.display.Sprite;
	import probs.Problem;
	
	/**
	 * <B>Problem 2</B>
	 * <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:</p>
	 * <p style="text-align:center;">1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</p>
	 * <p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
	 * @author Tim Wu <a href="http://wuzhiwei.net">http://wuzhiwei.net</a><br>
	 * 
	 */
	public class Prob2 extends Problem
	{
		private var length:int = 4000000;
		
		public function Prob2()
		{
			var a:int = 1;
			var b:int = 1;
			
			var temp:int = 0;
			var add:int = 0;
			while(b <= length)
			{
				temp = b;
				b += a;
				a = temp;
				if(b % 2 == 0 && b <= length)
				{
					add+=b;
				}
			}
			super.showAnswer(add);
		}
	}
}